"""Generate candidate re-observation goals from target search regions.

The original video-oriented helpers stay intact; the live exploration
candidates (plan section 9) are generated by
:func:`generate_live_exploration_candidates`.
"""

from __future__ import annotations

import math
from typing import Any

from .exploration_config import CandidateConfig
from .exploration_graph import ExplorationGraph
from .models import (
    GOAL_INSPECT_ANCHOR,
    GOAL_NAVIGATE_POSE,
    GOAL_RELATIVE_MOVE,
    GOAL_REOBSERVE,
    GOAL_REVISIT_NODE,
    GOAL_ROTATE_VIEW,
    ExplorationGoal,
    LiveObservation,
)
from .robot_backend import RobotCapabilities
from .models import NavigationWaypoint, VideoFramePose
from .priority import priority_to_confidence


def generate_candidate_goals(
    target_search_result: dict[str, Any],
    trajectory: list[VideoFramePose],
    max_candidates: int = 5,
) -> list[NavigationWaypoint]:
    regions = target_search_result.get("candidate_regions") or []
    goals: list[NavigationWaypoint] = []
    for index, region in enumerate(regions[:max_candidates]):
        frame_pose = _nearest_pose(trajectory, region.get("frame_id"))
        if frame_pose is None:
            continue
        goals.append(
            NavigationWaypoint(
                waypoint_id=f"candidate_{index:02d}",
                pose=frame_pose.pose,
                source_frame_id=frame_pose.frame_id,
                semantic_label=str(region.get("reason") or "候选区域重新观察"),
                waypoint_type="candidate",
                confidence=priority_to_confidence(region.get("priority"), 0.45),
                provenance={
                    "source": "candidate_regions",
                    "region": region,
                    "scale_verified": frame_pose.pose.scale_status == "metric",
                },
            )
        )
    return goals


def generate_live_exploration_candidates(
    *,
    observation: LiveObservation,
    graph: ExplorationGraph,
    directive: Any | None = None,
    anchor_labels: list[str] | None = None,
    negative_memory: Any = None,
    negative_target_key: str = "target",
    capabilities: RobotCapabilities | None = None,
    config: CandidateConfig | None = None,
    current_yaw_deg: float = 0.0,
    turn_only: bool = False,
    max_candidates: int = 12,
) -> list[ExplorationGoal]:
    """Build exploration goals from SemanticNavigation directive / unvisited sectors /
    graph nodes / semantic anchors / last-known / fallback (plan section 9)."""
    config = config or CandidateConfig()
    capabilities = capabilities or RobotCapabilities()
    cap = capabilities
    allowed_primitives = {
        str(item).upper() for item in (cap.allowed_motion_primitives or ())
    }
    # Older backends did not publish the explicit vocabulary; preserve their
    # existing behavior while making the Go2-W contract planner-visible.
    explicit_primitive_contract = bool(allowed_primitives)
    candidates: list[ExplorationGoal] = []
    seen: set[tuple[str, Any]] = set()
    sector_deg = 360.0 / max(1, config.heading_sectors)
    current_sector = int(round(current_yaw_deg / sector_deg))
    min_turn = max(1.0, float(getattr(config, "min_turn_deg", 5.0)))

    def add(goal: ExplorationGoal) -> None:
        if explicit_primitive_contract and not _goal_primitive_allowed(
            goal, allowed_primitives
        ):
            return
        # Skip tiny turns the platform executor will reject (e.g. <5 deg).
        if goal.goal_type in {GOAL_ROTATE_VIEW, GOAL_INSPECT_ANCHOR,
                              GOAL_REVISIT_NODE}:
            dyaw = float(goal.relative_dyaw or 0.0)
            if abs(dyaw) < min_turn:
                return
        source = str(goal.provenance.get("source", "unknown"))
        key = (goal.goal_type, goal.heading_sector, goal.target_node_id, source)
        if key in seen:
            return
        seen.add(key)
        candidates.append(goal)

    # A. SemanticNavigation semantic directive ----------------------------------------
    if directive is not None:
        kind = getattr(directive, "kind", None)
        kind_value = kind.value if hasattr(kind, "value") else str(kind or "")
        heading = getattr(directive, "preferred_heading_delta_deg", None)
        anchor_label = getattr(directive, "anchor_label", None)
        confidence = float(getattr(directive, "confidence", 0.0))
        directive_id = getattr(directive, "directive_id", "directive")
        if kind_value in {"inspect_anchor"} and anchor_label:
            add(
                ExplorationGoal(
                    goal_id=f"cand_{len(candidates) + 1:03d}",
                    goal_type=GOAL_INSPECT_ANCHOR,
                    relative_dyaw=_clamp_heading(heading, config.fallback_turn_deg),
                    semantic_anchor=str(anchor_label),
                    semantic_reason=f"semantic_navigation:{directive_id}",
                    heading_sector=_sector_for_delta(current_yaw_deg, heading, sector_deg),
                    semantic_relevance=max(0.4, confidence),
                    provenance={"source": "semantic_navigation_directive", "directive_id": directive_id,
                                "kind": kind_value},
                )
            )
        elif kind_value in {"explore_unseen", "reobserve_sector", "legacy_scan",
                            "hold_and_reobserve"}:
            if kind_value == "hold_and_reobserve":
                add(
                    ExplorationGoal(
                        goal_id=f"cand_{len(candidates) + 1:03d}",
                        goal_type=GOAL_REOBSERVE,
                        heading_sector=current_sector,
                        semantic_reason=f"semantic_navigation:{directive_id} hold and reobserve",
                        semantic_relevance=max(0.3, confidence),
                        provenance={"source": "semantic_navigation_directive", "directive_id": directive_id,
                                    "kind": kind_value},
                    )
                )
            elif isinstance(heading, (int, float)):
                add(
                    ExplorationGoal(
                        goal_id=f"cand_{len(candidates) + 1:03d}",
                        goal_type=GOAL_ROTATE_VIEW,
                        relative_dyaw=_clamp_heading(heading, config.fallback_turn_deg),
                        semantic_anchor=anchor_label,
                        semantic_reason=f"semantic_navigation:{directive_id}",
                        heading_sector=_sector_for_delta(current_yaw_deg, heading, sector_deg),
                        semantic_relevance=max(0.3, confidence),
                        provenance={"source": "semantic_navigation_directive", "directive_id": directive_id,
                                    "kind": kind_value},
                    )
                )

    # B. Unvisited heading sectors (relative mode) ---------------------------
    if not cap.supports_metric_navigation:
        for sector in range(config.heading_sectors):
            if graph.sector_visited_count(sector) > 0:
                continue
            delta = _delta_to_sector(current_yaw_deg, sector, sector_deg)
            if abs(delta) < 1.0:
                continue  # already facing this sector; observing it is the current view
            add(
                ExplorationGoal(
                    goal_id=f"cand_{len(candidates) + 1:03d}",
                    goal_type=GOAL_ROTATE_VIEW,
                    relative_dyaw=_clamp_heading(delta, config.fallback_turn_deg),
                    semantic_reason="unvisited heading sector",
                    heading_sector=sector,
                    expected_information_gain=config.unvisited_sector_bonus,
                    provenance={"source": "unvisited_sector", "sector": sector,
                                "delta_deg": round(delta, 2)},
                )
            )

    # C. Graph UNSEEN / SEMANTIC_INTEREST nodes (relative mode) ---------------
    if not cap.supports_metric_navigation:
        for node in graph.unvisited_nodes() + graph.semantic_interest_nodes():
            delta = _delta_to_heading(current_yaw_deg, node.heading, sector_deg)
            add(
                ExplorationGoal(
                    goal_id=f"cand_{len(candidates) + 1:03d}",
                    goal_type=GOAL_REVISIT_NODE,
                    target_node_id=node.node_id,
                    relative_dyaw=_clamp_heading(delta, config.fallback_turn_deg),
                    semantic_reason=f"graph node {node.node_id} ({node.reachable_state})",
                    heading_sector=node.heading_sector,
                    semantic_relevance=node.semantic_relevance,
                    expected_information_gain=node.information_gain,
                    provenance={"source": "graph_node", "node_id": node.node_id,
                                "state": node.reachable_state},
                )
            )

    # E. Last-known / target-lost (relative mode) -----------------------------
    if not cap.supports_metric_navigation:
        for node in graph.target_candidate_nodes():
            if observation.target_present:
                continue
            delta = _delta_to_heading(current_yaw_deg, node.heading, sector_deg)
            add(
                ExplorationGoal(
                    goal_id=f"cand_{len(candidates) + 1:03d}",
                    goal_type=GOAL_REVISIT_NODE,
                    target_node_id=node.node_id,
                    relative_dyaw=_clamp_heading(delta, config.fallback_turn_deg),
                    semantic_reason="last-known target candidate reobserve",
                    heading_sector=node.heading_sector,
                    semantic_relevance=config.last_known_revisit_priority,
                    provenance={"source": "last_known", "node_id": node.node_id},
                )
            )

    # D. Strong semantic anchors in the current view -------------------------
    if anchor_labels:
        for item in observation.scene_objects:
            label = str(item.get("label_zh") or item.get("label") or "").strip()
            if not label:
                continue
            if not any(anchor in label for anchor in anchor_labels):
                continue
            delta = _object_heading_delta(item)
            add(
                ExplorationGoal(
                    goal_id=f"cand_{len(candidates) + 1:03d}",
                    goal_type=GOAL_INSPECT_ANCHOR,
                    relative_dyaw=_clamp_heading(delta, config.fallback_turn_deg),
                    semantic_anchor=label,
                    semantic_reason=f"anchor {label} visible in current view",
                    heading_sector=_sector_for_delta(current_yaw_deg, delta, sector_deg),
                    semantic_relevance=0.8,
                    provenance={"source": "semantic_anchor", "anchor": label},
                )
            )

    # E. Last-known / target-lost -------------------------------------------
    for node in graph.target_candidate_nodes():
        if observation.target_present:
            continue
        delta = _delta_to_heading(current_yaw_deg, node.heading, sector_deg)
        add(
            ExplorationGoal(
                goal_id=f"cand_{len(candidates) + 1:03d}",
                goal_type=GOAL_REVISIT_NODE,
                target_node_id=node.node_id,
                relative_dyaw=_clamp_heading(delta, config.fallback_turn_deg),
                semantic_reason="last-known target candidate reobserve",
                heading_sector=node.heading_sector,
                semantic_relevance=config.last_known_revisit_priority,
                provenance={"source": "last_known", "node_id": node.node_id},
            )
        )

    # G. Metric navigation backend (future robot): map graph nodes and
    #    unvisited viewpoints to NAVIGATE_POSE goals.
    if cap.supports_metric_navigation:
        metric_added = False
        for node in graph.nodes.values():
            pose = getattr(node, "pose", None)
            if pose is None:
                continue
            add(
                ExplorationGoal(
                    goal_id=f"cand_{len(candidates) + 1:03d}",
                    goal_type=GOAL_NAVIGATE_POSE,
                    target_node_id=node.node_id,
                    position=(pose.x, pose.y),
                    yaw=node.heading if node.heading is not None else pose.yaw,
                    frame="map",
                    semantic_reason=f"metric viewpoint near node {node.node_id}",
                    heading_sector=node.heading_sector,
                    semantic_relevance=node.semantic_relevance,
                    expected_information_gain=node.information_gain,
                    provenance={"source": "metric_node_viewpoint",
                                "node_id": node.node_id},
                )
            )
            metric_added = True
        if not metric_added:
            # No mapped nodes yet: a short metric step to a viewpoint ahead.
            dx = 0.5
            yaw_rad = current_yaw_deg * 3.141592653589793 / 180.0
            add(
                ExplorationGoal(
                    goal_id=f"cand_{len(candidates) + 1:03d}",
                    goal_type=GOAL_NAVIGATE_POSE,
                    position=(dx * math.cos(yaw_rad), dx * math.sin(yaw_rad)),
                    yaw=current_yaw_deg,
                    frame="map",
                    semantic_reason="metric bootstrap viewpoint",
                    provenance={"source": "metric_bootstrap"},
                )
            )

    # F. Fallback exploration ------------------------------------------------
    if not cap.supports_metric_navigation:
        if not candidates:
            for sector in sorted(
                range(config.heading_sectors),
                key=lambda s: _sector_distance(current_sector, s, config.heading_sectors),
            )[:4]:
                delta = _delta_to_sector(current_yaw_deg, sector, sector_deg)
                add(
                    ExplorationGoal(
                        goal_id=f"cand_{len(candidates) + 1:03d}",
                        goal_type=GOAL_ROTATE_VIEW,
                        relative_dyaw=_clamp_heading(delta, config.fallback_turn_deg),
                        semantic_reason="fallback exploration",
                        heading_sector=sector,
                        provenance={"source": "fallback", "sector": sector},
                    )
                )
        if (
            cap.supports_relative_translation
            and not turn_only
            and (
                not explicit_primitive_contract
                or "FORWARD" in allowed_primitives
            )
        ):
            add(
                ExplorationGoal(
                    goal_id=f"cand_{len(candidates) + 1:03d}",
                    goal_type=GOAL_RELATIVE_MOVE,
                    relative_dx=0.20,
                    semantic_reason="short forward to change viewpoint",
                    provenance={"source": "fallback_forward"},
                )
            )
    if negative_memory is not None:
        for candidate in candidates:
            if candidate.heading_sector is None:
                continue
            try:
                penalty, refs = negative_memory.sector_penalty(
                    negative_target_key, candidate.heading_sector
                )
            except Exception:
                penalty, refs = 0.0, []
            if penalty > 0.0:
                candidate.provenance["negative_memory_penalty"] = round(penalty, 3)
                candidate.provenance["negative_memory_refs"] = refs
    candidates.sort(
        key=lambda item: (
            item.semantic_relevance + item.expected_information_gain,
            -abs(item.relative_dyaw or 0.0),
        ),
        reverse=True,
    )
    return candidates[:max_candidates]


def _goal_primitive_allowed(
    goal: ExplorationGoal, allowed_primitives: set[str]
) -> bool:
    """Return whether a high-level goal maps to the backend vocabulary.

    Unsupported lateral/reverse goals are intentionally filtered before the
    Go2-W executor.  The backend still rejects malformed/external goals with
    a replan-required result, so this is a planner capability contract rather
    than a trust boundary.
    """
    if goal.goal_type in {GOAL_ROTATE_VIEW, GOAL_INSPECT_ANCHOR,
                          GOAL_REVISIT_NODE}:
        dyaw = float(goal.relative_dyaw or 0.0)
        primitive = "ROTATE_LEFT" if dyaw >= 0.0 else "ROTATE_RIGHT"
        return primitive in allowed_primitives
    if goal.goal_type == GOAL_RELATIVE_MOVE:
        dx = float(goal.relative_dx or 0.0)
        dy = float(goal.relative_dy or 0.0)
        if dx < -0.01:
            return "REVERSE" in allowed_primitives
        if abs(dy) > 0.01:
            return "LATERAL" in allowed_primitives
        return "FORWARD" in allowed_primitives
    return True


def _nearest_pose(trajectory: list[VideoFramePose], frame_id) -> VideoFramePose | None:
    if not trajectory:
        return None
    if frame_id is None:
        return trajectory[-1]
    target = int(frame_id)
    return min(trajectory, key=lambda item: abs(item.frame_id - target))


def _clamp_heading(delta: Any, limit_deg: float) -> float:
    if not isinstance(delta, (int, float)):
        return 0.0
    value = (float(delta) + 180.0) % 360.0 - 180.0
    return max(-abs(limit_deg), min(abs(limit_deg), value))


def _delta_to_sector(current_yaw_deg: float, sector: int, sector_deg: float) -> float:
    target = sector * sector_deg
    return (target - current_yaw_deg + 180.0) % 360.0 - 180.0


def _delta_to_heading(current_yaw_deg: float, heading: float | None,
                      sector_deg: float) -> float:
    if heading is None:
        return 0.0
    return (float(heading) - current_yaw_deg + 180.0) % 360.0 - 180.0


def _sector_for_delta(current_yaw_deg: float, delta: Any, sector_deg: float) -> int:
    if not isinstance(delta, (int, float)):
        return int(round(current_yaw_deg / sector_deg)) % max(1, int(round(360.0 / sector_deg)))
    target = current_yaw_deg + float(delta)
    sectors = max(1, int(round(360.0 / sector_deg)))
    return int(round(target / sector_deg)) % sectors


def _sector_distance(first: int, second: int, sectors: int) -> int:
    diff = abs(first - second) % sectors
    return min(diff, sectors - diff)


def _object_heading_delta(item: dict[str, Any]) -> float:
    position = str(item.get("position_2d") or item.get("position") or "")
    if isinstance(item.get("position"), dict):
        position = str(item["position"].get("horizontal") or "")
    if "left" in position or "左" in position:
        return 25.0
    if "right" in position or "右" in position:
        return -25.0
    bbox = item.get("bbox_2d") or item.get("bbox")
    if isinstance(bbox, list) and len(bbox) == 4:
        center = (float(bbox[0]) + float(bbox[2])) / 2.0
        if center < 0.4:
            return 25.0
        if center > 0.6:
            return -25.0
    return 10.0
